/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables;


import com.ke.bella.openapi.DefaultSchema;
import com.ke.bella.openapi.Indexes;
import com.ke.bella.openapi.Keys;
import com.ke.bella.openapi.tables.records.Hive2mysqlBillingMonthRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 每月账单
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hive2mysqlBillingMonth extends TableImpl<Hive2mysqlBillingMonthRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>hive2mysql_billing_month</code>
     */
    public static final Hive2mysqlBillingMonth HIVE2MYSQL_BILLING_MONTH = new Hive2mysqlBillingMonth();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Hive2mysqlBillingMonthRecord> getRecordType() {
        return Hive2mysqlBillingMonthRecord.class;
    }

    /**
     * The column <code>hive2mysql_billing_month.id</code>. 主键ID
     */
    public final TableField<Hive2mysqlBillingMonthRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>hive2mysql_billing_month.pt</code>. 时间
     */
    public final TableField<Hive2mysqlBillingMonthRecord, String> PT = createField(DSL.name("pt"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "时间");

    /**
     * The column <code>hive2mysql_billing_month.endpoint</code>. 能力点
     */
    public final TableField<Hive2mysqlBillingMonthRecord, String> ENDPOINT = createField(DSL.name("endpoint"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "能力点");

    /**
     * The column <code>hive2mysql_billing_month.model</code>. 模型名称
     */
    public final TableField<Hive2mysqlBillingMonthRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "模型名称");

    /**
     * The column <code>hive2mysql_billing_month.account_type</code>. 账户类型
     */
    public final TableField<Hive2mysqlBillingMonthRecord, String> ACCOUNT_TYPE = createField(DSL.name("account_type"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "账户类型");

    /**
     * The column <code>hive2mysql_billing_month.account_code</code>. 账户编码
     */
    public final TableField<Hive2mysqlBillingMonthRecord, String> ACCOUNT_CODE = createField(DSL.name("account_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "账户编码");

    /**
     * The column <code>hive2mysql_billing_month.ak_code</code>. ak编码
     */
    public final TableField<Hive2mysqlBillingMonthRecord, String> AK_CODE = createField(DSL.name("ak_code"), SQLDataType.VARCHAR(64), this, "ak编码");

    /**
     * The column <code>hive2mysql_billing_month.amount</code>.
     */
    public final TableField<Hive2mysqlBillingMonthRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.DECIMAL(20, 4).nullable(false).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>hive2mysql_billing_month.ctime</code>.
     */
    public final TableField<Hive2mysqlBillingMonthRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>hive2mysql_billing_month.mtime</code>.
     */
    public final TableField<Hive2mysqlBillingMonthRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Hive2mysqlBillingMonth(Name alias, Table<Hive2mysqlBillingMonthRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hive2mysqlBillingMonth(Name alias, Table<Hive2mysqlBillingMonthRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("每月账单"), TableOptions.table());
    }

    /**
     * Create an aliased <code>hive2mysql_billing_month</code> table reference
     */
    public Hive2mysqlBillingMonth(String alias) {
        this(DSL.name(alias), HIVE2MYSQL_BILLING_MONTH);
    }

    /**
     * Create an aliased <code>hive2mysql_billing_month</code> table reference
     */
    public Hive2mysqlBillingMonth(Name alias) {
        this(alias, HIVE2MYSQL_BILLING_MONTH);
    }

    /**
     * Create a <code>hive2mysql_billing_month</code> table reference
     */
    public Hive2mysqlBillingMonth() {
        this(DSL.name("hive2mysql_billing_month"), null);
    }

    public <O extends Record> Hive2mysqlBillingMonth(Table<O> child, ForeignKey<O, Hive2mysqlBillingMonthRecord> key) {
        super(child, key, HIVE2MYSQL_BILLING_MONTH);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HIVE2MYSQL_BILLING_MONTH_IDX_ACCOUNT_TYPE_CODE, Indexes.HIVE2MYSQL_BILLING_MONTH_IDX_AK_CODE_ENDPOINT_MODEL_PT, Indexes.HIVE2MYSQL_BILLING_MONTH_IDX_AK_CODE_PT);
    }

    @Override
    public Identity<Hive2mysqlBillingMonthRecord, Long> getIdentity() {
        return (Identity<Hive2mysqlBillingMonthRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<Hive2mysqlBillingMonthRecord> getPrimaryKey() {
        return Keys.KEY_HIVE2MYSQL_BILLING_MONTH_PRIMARY;
    }

    @Override
    public List<UniqueKey<Hive2mysqlBillingMonthRecord>> getKeys() {
        return Arrays.<UniqueKey<Hive2mysqlBillingMonthRecord>>asList(Keys.KEY_HIVE2MYSQL_BILLING_MONTH_PRIMARY);
    }

    @Override
    public Hive2mysqlBillingMonth as(String alias) {
        return new Hive2mysqlBillingMonth(DSL.name(alias), this);
    }

    @Override
    public Hive2mysqlBillingMonth as(Name alias) {
        return new Hive2mysqlBillingMonth(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hive2mysqlBillingMonth rename(String name) {
        return new Hive2mysqlBillingMonth(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hive2mysqlBillingMonth rename(Name name) {
        return new Hive2mysqlBillingMonth(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, String, String, String, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
