/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi;


import com.ke.bella.openapi.tables.Apikey;
import com.ke.bella.openapi.tables.ApikeyChangeLog;
import com.ke.bella.openapi.tables.ApikeyMonthCost;
import com.ke.bella.openapi.tables.ApikeyTransferLog;
import com.ke.bella.openapi.tables.Category;
import com.ke.bella.openapi.tables.Channel;
import com.ke.bella.openapi.tables.Endpoint;
import com.ke.bella.openapi.tables.EndpointCategoryRel;
import com.ke.bella.openapi.tables.Hive2mysqlBillingDaily;
import com.ke.bella.openapi.tables.Hive2mysqlBillingMonth;
import com.ke.bella.openapi.tables.Hive2mysqlBillingPerHour;
import com.ke.bella.openapi.tables.Model;
import com.ke.bella.openapi.tables.ModelAuthorizerRel;
import com.ke.bella.openapi.tables.ModelEndpointRel;
import com.ke.bella.openapi.tables.SpaceMember;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index HIVE2MYSQL_BILLING_DAILY_IDX_ACCOUNT_TYPE_CODE = Internal.createIndex(DSL.name("idx_account_type_code"), Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY, new OrderField[] { Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY.ACCOUNT_TYPE, Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY.ACCOUNT_CODE }, false);
    public static final Index HIVE2MYSQL_BILLING_MONTH_IDX_ACCOUNT_TYPE_CODE = Internal.createIndex(DSL.name("idx_account_type_code"), Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH, new OrderField[] { Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.ACCOUNT_TYPE, Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.ACCOUNT_CODE }, false);
    public static final Index HIVE2MYSQL_BILLING_PER_HOUR_IDX_ACCOUNT_TYPE_CODE = Internal.createIndex(DSL.name("idx_account_type_code"), Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR, new OrderField[] { Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR.ACCOUNT_TYPE, Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR.ACCOUNT_CODE }, false);
    public static final Index APIKEY_CHANGE_LOG_IDX_ACTION_TYPE = Internal.createIndex(DSL.name("idx_action_type"), ApikeyChangeLog.APIKEY_CHANGE_LOG, new OrderField[] { ApikeyChangeLog.APIKEY_CHANGE_LOG.ACTION_TYPE }, false);
    public static final Index APIKEY_CHANGE_LOG_IDX_AK_CODE = Internal.createIndex(DSL.name("idx_ak_code"), ApikeyChangeLog.APIKEY_CHANGE_LOG, new OrderField[] { ApikeyChangeLog.APIKEY_CHANGE_LOG.AK_CODE }, false);
    public static final Index APIKEY_TRANSFER_LOG_IDX_AK_CODE = Internal.createIndex(DSL.name("idx_ak_code"), ApikeyTransferLog.APIKEY_TRANSFER_LOG, new OrderField[] { ApikeyTransferLog.APIKEY_TRANSFER_LOG.AK_CODE }, false);

    public static final Index HIVE2MYSQL_BILLING_DAILY_IDX_AK_CODE_ENDPOINT_MODEL_PT = Internal.createIndex(DSL.name("idx_ak_code_endpoint_model_pt"), Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY, new OrderField[] { Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY.AK_CODE, Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY.ENDPOINT, Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY.MODEL, Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY.PT }, false);
    public static final Index HIVE2MYSQL_BILLING_MONTH_IDX_AK_CODE_ENDPOINT_MODEL_PT = Internal.createIndex(DSL.name("idx_ak_code_endpoint_model_pt"), Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH, new OrderField[] { Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.AK_CODE, Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.ENDPOINT, Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.MODEL, Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.PT }, false);
    public static final Index HIVE2MYSQL_BILLING_PER_HOUR_IDX_AK_CODE_ENDPOINT_MODEL_PT = Internal.createIndex(DSL.name("idx_ak_code_endpoint_model_pt"), Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR, new OrderField[] { Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR.AK_CODE, Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR.ENDPOINT, Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR.MODEL, Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR.PT }, false);
    public static final Index HIVE2MYSQL_BILLING_DAILY_IDX_AK_CODE_PT = Internal.createIndex(DSL.name("idx_ak_code_pt"), Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY, new OrderField[] { Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY.AK_CODE, Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY.PT }, false);
    public static final Index HIVE2MYSQL_BILLING_MONTH_IDX_AK_CODE_PT = Internal.createIndex(DSL.name("idx_ak_code_pt"), Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH, new OrderField[] { Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.AK_CODE, Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.PT }, false);
    public static final Index HIVE2MYSQL_BILLING_PER_HOUR_IDX_AK_CODE_PT = Internal.createIndex(DSL.name("idx_ak_code_pt"), Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR, new OrderField[] { Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR.AK_CODE, Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR.PT }, false);
    public static final Index MODEL_AUTHORIZER_REL_IDX_AUTHORIZER_CODE = Internal.createIndex(DSL.name("idx_authorizer_code"), ModelAuthorizerRel.MODEL_AUTHORIZER_REL, new OrderField[] { ModelAuthorizerRel.MODEL_AUTHORIZER_REL.AUTHORIZER_CODE }, false);
    public static final Index ENDPOINT_CATEGORY_REL_IDX_CATEGORY_CODE = Internal.createIndex(DSL.name("idx_category_code"), EndpointCategoryRel.ENDPOINT_CATEGORY_REL, new OrderField[] { EndpointCategoryRel.ENDPOINT_CATEGORY_REL.CATEGORY_CODE }, false);
    public static final Index CATEGORY_IDX_CATEGORY_NAME = Internal.createIndex(DSL.name("idx_category_name"), Category.CATEGORY, new OrderField[] { Category.CATEGORY.CATEGORY_NAME }, false);

    public static final Index APIKEY_CHANGE_LOG_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), ApikeyChangeLog.APIKEY_CHANGE_LOG, new OrderField[] { ApikeyChangeLog.APIKEY_CHANGE_LOG.CTIME }, false);
    public static final Index APIKEY_TRANSFER_LOG_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), ApikeyTransferLog.APIKEY_TRANSFER_LOG, new OrderField[] { ApikeyTransferLog.APIKEY_TRANSFER_LOG.CTIME }, false);
    public static final Index CHANNEL_IDX_ENTITY_TYPE_CODE = Internal.createIndex(DSL.name("idx_entity_type_code"), Channel.CHANNEL, new OrderField[] { Channel.CHANNEL.ENTITY_TYPE, Channel.CHANNEL.ENTITY_CODE }, false);
    public static final Index APIKEY_TRANSFER_LOG_IDX_FROM_OWNER = Internal.createIndex(DSL.name("idx_from_owner"), ApikeyTransferLog.APIKEY_TRANSFER_LOG, new OrderField[] { ApikeyTransferLog.APIKEY_TRANSFER_LOG.FROM_OWNER_TYPE, ApikeyTransferLog.APIKEY_TRANSFER_LOG.FROM_OWNER_CODE }, false);
    public static final Index APIKEY_IDX_MANAGER_CODE = Internal.createIndex(DSL.name("idx_manager_code"), Apikey.APIKEY, new OrderField[] { Apikey.APIKEY.MANAGER_CODE }, false);
    public static final Index SPACE_MEMBER_IDX_MEMBER_UID = Internal.createIndex(DSL.name("idx_member_uid"), SpaceMember.SPACE_MEMBER, new OrderField[] { SpaceMember.SPACE_MEMBER.MEMBER_UID }, false);

    public static final Index MODEL_ENDPOINT_REL_IDX_MODEL_NAME = Internal.createIndex(DSL.name("idx_model_name"), ModelEndpointRel.MODEL_ENDPOINT_REL, new OrderField[] { ModelEndpointRel.MODEL_ENDPOINT_REL.MODEL_NAME }, false);
    public static final Index APIKEY_MONTH_COST_IDX_MONTH = Internal.createIndex(DSL.name("idx_month"), ApikeyMonthCost.APIKEY_MONTH_COST, new OrderField[] { ApikeyMonthCost.APIKEY_MONTH_COST.MONTH }, false);
    public static final Index MODEL_IDX_OWNER_NAME = Internal.createIndex(DSL.name("idx_owner_name"), Model.MODEL, new OrderField[] { Model.MODEL.OWNER_NAME }, false);
    public static final Index APIKEY_IDX_OWNER_TYPE_CODE = Internal.createIndex(DSL.name("idx_owner_type_code"), Apikey.APIKEY, new OrderField[] { Apikey.APIKEY.OWNER_TYPE, Apikey.APIKEY.OWNER_CODE }, false);
    public static final Index MODEL_IDX_OWNER_TYPE_CODE = Internal.createIndex(DSL.name("idx_owner_type_code"), Model.MODEL, new OrderField[] { Model.MODEL.OWNER_TYPE, Model.MODEL.OWNER_CODE }, false);
    public static final Index APIKEY_IDX_PARENT_OUT_ENTITY_CODE = Internal.createIndex(DSL.name("idx_parent_out_entity_code"), Apikey.APIKEY, new OrderField[] { Apikey.APIKEY.PARENT_CODE, Apikey.APIKEY.OUT_ENTITY_CODE }, false);
    public static final Index CHANNEL_IDX_PROTOCOL = Internal.createIndex(DSL.name("idx_protocol"), Channel.CHANNEL, new OrderField[] { Channel.CHANNEL.PROTOCOL }, false);
    public static final Index CHANNEL_IDX_QUEUE_NAME = Internal.createIndex(DSL.name("idx_queue_name"), Channel.CHANNEL, new OrderField[] { Channel.CHANNEL.QUEUE_NAME }, false);
    public static final Index ENDPOINT_CATEGORY_REL_IDX_SORT = Internal.createIndex(DSL.name("idx_sort"), EndpointCategoryRel.ENDPOINT_CATEGORY_REL, new OrderField[] { EndpointCategoryRel.ENDPOINT_CATEGORY_REL.SORT }, false);

    public static final Index CHANNEL_IDX_SUPPLIER = Internal.createIndex(DSL.name("idx_supplier"), Channel.CHANNEL, new OrderField[] { Channel.CHANNEL.SUPPLIER }, false);
    public static final Index APIKEY_TRANSFER_LOG_IDX_TO_OWNER = Internal.createIndex(DSL.name("idx_to_owner"), ApikeyTransferLog.APIKEY_TRANSFER_LOG, new OrderField[] { ApikeyTransferLog.APIKEY_TRANSFER_LOG.TO_OWNER_TYPE, ApikeyTransferLog.APIKEY_TRANSFER_LOG.TO_OWNER_CODE }, false);
    public static final Index ENDPOINT_UNIQ_IDX_UNI_ENDPOINT_NAME = Internal.createIndex(DSL.name("uniq_idx_uni_endpoint_name"), Endpoint.ENDPOINT, new OrderField[] { Endpoint.ENDPOINT.ENDPOINT_NAME }, false);
}
