/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi;


import com.ke.bella.openapi.tables.Apikey;
import com.ke.bella.openapi.tables.ApikeyChangeLog;
import com.ke.bella.openapi.tables.ApikeyMonthCost;
import com.ke.bella.openapi.tables.ApikeyRole;
import com.ke.bella.openapi.tables.ApikeyTransferLog;
import com.ke.bella.openapi.tables.Category;
import com.ke.bella.openapi.tables.Channel;
import com.ke.bella.openapi.tables.Endpoint;
import com.ke.bella.openapi.tables.EndpointCategoryRel;
import com.ke.bella.openapi.tables.Hive2mysqlBillingDaily;
import com.ke.bella.openapi.tables.Hive2mysqlBillingMonth;
import com.ke.bella.openapi.tables.Hive2mysqlBillingPerHour;
import com.ke.bella.openapi.tables.Instance;
import com.ke.bella.openapi.tables.Model;
import com.ke.bella.openapi.tables.ModelAuthorizerRel;
import com.ke.bella.openapi.tables.ModelEndpointRel;
import com.ke.bella.openapi.tables.Space;
import com.ke.bella.openapi.tables.SpaceMember;
import com.ke.bella.openapi.tables.SpaceRole;
import com.ke.bella.openapi.tables.User;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * ak
     */
    public static final Apikey APIKEY = Apikey.APIKEY;

    /**
     * API Key变更历史表
     */
    public static final ApikeyChangeLog APIKEY_CHANGE_LOG = ApikeyChangeLog.APIKEY_CHANGE_LOG;


    /**
     * ak月花费
     */
    public static final ApikeyMonthCost APIKEY_MONTH_COST = ApikeyMonthCost.APIKEY_MONTH_COST;

    /**
     * ak角色
     */
    public static final ApikeyRole APIKEY_ROLE = ApikeyRole.APIKEY_ROLE;

    /**
     * API Key所有权转移审计日志表
     */
    public static final ApikeyTransferLog APIKEY_TRANSFER_LOG = ApikeyTransferLog.APIKEY_TRANSFER_LOG;

    /**
     * 类目
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * 通道
     */
    public static final Channel CHANNEL = Channel.CHANNEL;

    /**
     * 能力点
     */
    public static final Endpoint ENDPOINT = Endpoint.ENDPOINT;

    /**
     * 能力点类目
     */
    public static final EndpointCategoryRel ENDPOINT_CATEGORY_REL = EndpointCategoryRel.ENDPOINT_CATEGORY_REL;

    /**
     * 每日账单
     */
    public static final Hive2mysqlBillingDaily HIVE2MYSQL_BILLING_DAILY = Hive2mysqlBillingDaily.HIVE2MYSQL_BILLING_DAILY;

    /**
     * 每月账单
     */
    public static final Hive2mysqlBillingMonth HIVE2MYSQL_BILLING_MONTH = Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH;

    /**
     * 每小时账单
     */
    public static final Hive2mysqlBillingPerHour HIVE2MYSQL_BILLING_PER_HOUR = Hive2mysqlBillingPerHour.HIVE2MYSQL_BILLING_PER_HOUR;

    /**
     * The table <code>instance</code>.
     */
    public static final Instance INSTANCE = Instance.INSTANCE;

    /**
     * 模型
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * 模型授权信息
     */
    public static final ModelAuthorizerRel MODEL_AUTHORIZER_REL = ModelAuthorizerRel.MODEL_AUTHORIZER_REL;

    /**
     * 模型能力点
     */
    public static final ModelEndpointRel MODEL_ENDPOINT_REL = ModelEndpointRel.MODEL_ENDPOINT_REL;

    /**
     * 空间表
     */
    public static final Space SPACE = Space.SPACE;

    /**
     * 空间成员信息表
     */
    public static final SpaceMember SPACE_MEMBER = SpaceMember.SPACE_MEMBER;

    /**
     * 空间角色表
     */
    public static final SpaceRole SPACE_ROLE = SpaceRole.SPACE_ROLE;

    /**
     * 用户表
     */
    public static final User USER = User.USER;
}
