/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.pojos;


import com.ke.bella.openapi.db.repo.Timed;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * 每月账单
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hive2mysqlBillingMonthDB implements Timed, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        pt;
    private String        endpoint;
    private String        model;
    private String        accountType;
    private String        accountCode;
    private String        akCode;
    private BigDecimal    amount;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public Hive2mysqlBillingMonthDB() {}

    public Hive2mysqlBillingMonthDB(Hive2mysqlBillingMonthDB value) {
        this.id = value.id;
        this.pt = value.pt;
        this.endpoint = value.endpoint;
        this.model = value.model;
        this.accountType = value.accountType;
        this.accountCode = value.accountCode;
        this.akCode = value.akCode;
        this.amount = value.amount;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public Hive2mysqlBillingMonthDB(
        Long          id,
        String        pt,
        String        endpoint,
        String        model,
        String        accountType,
        String        accountCode,
        String        akCode,
        BigDecimal    amount,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.pt = pt;
        this.endpoint = endpoint;
        this.model = model;
        this.accountType = accountType;
        this.accountCode = accountCode;
        this.akCode = akCode;
        this.amount = amount;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.pt</code>. 时间
     */
    public String getPt() {
        return this.pt;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.pt</code>. 时间
     */
    public void setPt(String pt) {
        this.pt = pt;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.endpoint</code>. 能力点
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.endpoint</code>. 能力点
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.model</code>. 模型名称
     */
    public String getModel() {
        return this.model;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.model</code>. 模型名称
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.account_type</code>. 账户类型
     */
    public String getAccountType() {
        return this.accountType;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.account_type</code>. 账户类型
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.account_code</code>. 账户编码
     */
    public String getAccountCode() {
        return this.accountCode;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.account_code</code>. 账户编码
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.ak_code</code>. ak编码
     */
    public String getAkCode() {
        return this.akCode;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.ak_code</code>. ak编码
     */
    public void setAkCode(String akCode) {
        this.akCode = akCode;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.amount</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>hive2mysql_billing_month.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>hive2mysql_billing_month.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Hive2mysqlBillingMonthDB (");

        sb.append(id);
        sb.append(", ").append(pt);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(model);
        sb.append(", ").append(accountType);
        sb.append(", ").append(accountCode);
        sb.append(", ").append(akCode);
        sb.append(", ").append(amount);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
