-- Variables are injected by the K8s test launcher before these fixtures run.
INSERT INTO apikey (
    code,
    ak_sha,
    ak_display,
    name,
    parent_code,
    out_entity_code,
    service_id,
    owner_type,
    owner_code,
    owner_name,
    manager_code,
    manager_name,
    role_code,
    certify_code,
    safety_scene_code,
    safety_level,
    month_quota,
    qps_limit,
    status,
    remark,
    cuid,
    cu_name,
    muid,
    mu_name
) VALUES (
    @test_apikey_code,
    @test_apikey_hash,
    @test_apikey_display,
    @test_apikey_name,
    '',
    '',
    '',
    'system',
    '0',
    'system',
    '',
    '',
    'all',
    '',
    '',
    100,
    50000.00,
    200,
    'active',
    'test only',
    0,
    'system',
    0,
    'system'
)
ON DUPLICATE KEY UPDATE
    ak_sha = VALUES(ak_sha),
    ak_display = VALUES(ak_display),
    name = VALUES(name),
    role_code = VALUES(role_code),
    safety_level = VALUES(safety_level),
    month_quota = VALUES(month_quota),
    qps_limit = VALUES(qps_limit),
    status = VALUES(status),
    remark = VALUES(remark),
    muid = VALUES(muid),
    mu_name = VALUES(mu_name);
