/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.openapi.tables.records;


import com.ke.bella.openapi.db.repo.Timed;
import com.ke.bella.openapi.tables.Hive2mysqlBillingMonth;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 每月账单
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hive2mysqlBillingMonthRecord extends UpdatableRecordImpl<Hive2mysqlBillingMonthRecord> implements Timed, Record10<Long, String, String, String, String, String, String, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>hive2mysql_billing_month.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.pt</code>. 时间
     */
    public void setPt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.pt</code>. 时间
     */
    public String getPt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.endpoint</code>. 能力点
     */
    public void setEndpoint(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.endpoint</code>. 能力点
     */
    public String getEndpoint() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.model</code>. 模型名称
     */
    public void setModel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.model</code>. 模型名称
     */
    public String getModel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.account_type</code>. 账户类型
     */
    public void setAccountType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.account_type</code>. 账户类型
     */
    public String getAccountType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.account_code</code>. 账户编码
     */
    public void setAccountCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.account_code</code>. 账户编码
     */
    public String getAccountCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.ak_code</code>. ak编码
     */
    public void setAkCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.ak_code</code>. ak编码
     */
    public String getAkCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>hive2mysql_billing_month.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>hive2mysql_billing_month.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, String, String, String, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, String, String, String, String, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.ID;
    }

    @Override
    public Field<String> field2() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.PT;
    }

    @Override
    public Field<String> field3() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.ENDPOINT;
    }

    @Override
    public Field<String> field4() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.MODEL;
    }

    @Override
    public Field<String> field5() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.ACCOUNT_TYPE;
    }

    @Override
    public Field<String> field6() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.ACCOUNT_CODE;
    }

    @Override
    public Field<String> field7() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.AK_CODE;
    }

    @Override
    public Field<BigDecimal> field8() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.AMOUNT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.CTIME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPt();
    }

    @Override
    public String component3() {
        return getEndpoint();
    }

    @Override
    public String component4() {
        return getModel();
    }

    @Override
    public String component5() {
        return getAccountType();
    }

    @Override
    public String component6() {
        return getAccountCode();
    }

    @Override
    public String component7() {
        return getAkCode();
    }

    @Override
    public BigDecimal component8() {
        return getAmount();
    }

    @Override
    public LocalDateTime component9() {
        return getCtime();
    }

    @Override
    public LocalDateTime component10() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPt();
    }

    @Override
    public String value3() {
        return getEndpoint();
    }

    @Override
    public String value4() {
        return getModel();
    }

    @Override
    public String value5() {
        return getAccountType();
    }

    @Override
    public String value6() {
        return getAccountCode();
    }

    @Override
    public String value7() {
        return getAkCode();
    }

    @Override
    public BigDecimal value8() {
        return getAmount();
    }

    @Override
    public LocalDateTime value9() {
        return getCtime();
    }

    @Override
    public LocalDateTime value10() {
        return getMtime();
    }

    @Override
    public Hive2mysqlBillingMonthRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value2(String value) {
        setPt(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value3(String value) {
        setEndpoint(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value4(String value) {
        setModel(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value5(String value) {
        setAccountType(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value6(String value) {
        setAccountCode(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value7(String value) {
        setAkCode(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value8(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value9(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord value10(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public Hive2mysqlBillingMonthRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, BigDecimal value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Hive2mysqlBillingMonthRecord
     */
    public Hive2mysqlBillingMonthRecord() {
        super(Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH);
    }

    /**
     * Create a detached, initialised Hive2mysqlBillingMonthRecord
     */
    public Hive2mysqlBillingMonthRecord(Long id, String pt, String endpoint, String model, String accountType, String accountCode, String akCode, BigDecimal amount, LocalDateTime ctime, LocalDateTime mtime) {
        super(Hive2mysqlBillingMonth.HIVE2MYSQL_BILLING_MONTH);

        setId(id);
        setPt(pt);
        setEndpoint(endpoint);
        setModel(model);
        setAccountType(accountType);
        setAccountCode(accountCode);
        setAkCode(akCode);
        setAmount(amount);
        setCtime(ctime);
        setMtime(mtime);
    }
}
